package ShapeType;

public enum ShapeType {
    EQUILATERAL_TRIANGLE,
    ISOSCELES_TRIANGLE,
    SCALENE_TRIANGLE,
    NOT_TRIANGLE,
    SQUARE,
    RECTANGLE,
    TRAPEZIUM,
    KITE,
    SQUARE_WITH_ALL_DIFFERENT_SIDES,
    NOT_QUADRILATERAL;
}
